### PR TITLE
Fix path variable in fail message

### PR DESCRIPTION
**Pull request by fwal**
Just a simple fix 🙂

### CODE REVIEW

**Review by danpalmer — APPROVED** [review]

**Comment by fwal** [comment]
Thanks! Though I just realised that I didn't follow semantic-release format for the commit 😬

**Comment by danpalmer** [comment]
No problem. That stuff all came from a template project and I have no idea how it works so I’m just ignoring it for now.

I’m afraid I won’t be able to do a release until I can set aside some time to figure out how to do it again. Unfortunately the whole process seems overly complex and I’m very unfamiliar with the ecosystem.

**Comment by fwal** [comment]
No worries. If you still have npm setup on your computer (check by running `npm whoami`) you should just be able to do `npm version patch` to bump the version number and then `npm publish` to deploy it!

Let me know if I can help out in any way 🙂

**Comment by fwal** [comment]
Just a heads-up. It doesn't look like the latest version was deployed successfully. While npm lists `0.1.1` on the web, it looks like it can't be downloaded 😢

**Pull request merged**
